// Code generated by "stringer -type=AusterityLevel"; DO NOT EDIT

package unilog

import "fmt"

const _AusterityLevel_name = "SheddableSheddablePlusCriticalCriticalPlus"

var _AusterityLevel_index = [...]uint8{0, 9, 22, 30, 42}

func (i AusterityLevel) String() string {
	if i < 0 || i >= AusterityLevel(len(_AusterityLevel_index)-1) {
		return fmt.Sprintf("AusterityLevel(%d)", i)
	}
	return _AusterityLevel_name[_AusterityLevel_index[i]:_AusterityLevel_index[i+1]]
}
